name: Build GDrive CLI

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get https://github.com/msfjarvis/gdrive code
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        cd $HOME
        git clone https://github.com/msfjarvis/gdrive.git
    
    - name: Change CLIENT ID & SECRET
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        cd $HOME/gdrive/
        sed -i "s/367116221053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com/$CLIENT_ID/g" handlers_drive.go
        sed -i "s/1qsNodXNaWq1mQuBjUjmvhoO/$CLIENT_SECRET/g" handlers_drive.go

    - name: Build
      run: |
        cp -r build/* $HOME/gdrive
        cd $HOME/gdrive/
        chmod +x build-selected.sh
        chmod +x build.sh
        ./build-selected.sh
        ls -al _release/bin

    - name: Copy release file
      run: |
        mkdir release
        cp -r $HOME/gdrive/_release/bin/* release

    - name: Save build file to artifact
      uses: actions/upload-artifact@v1
      with:
        name: release
        path: release
